### ISSUE TITLE
TypeError: join() argument must be str or bytes, not 'dict'

### ISSUE THREAD

**Issue by steam0111** [thatbrguy/Object-Detection-Quidditch#1]
We tried to run your NN , with your data set, but we got a few errors.

**Error 1 :**

We try :
> python create_tf_record.py \
> —data_dir='pwd' \
> —output_dir='pwd'

We got :
Use specific 'len(elem)' or 'elem is not None' test instead.
if not xml:

We repair it use `if xml is None:`, but we got another error

**Error 2 :**
We again try :
> python create_tf_record.py \
> —data_dir='pwd' \
> —output_dir='pwd'

We got
TypeError: join() argument must be str or bytes, not 'dict'

In file create_tf_record.py in `dict_to_tf_example()` we "print" return data of function `recursive_parse_xml_to_dict()` and it was empty , and then script got error.

**Comment by thatbrguy** [comment]
Hello. Can you tell exactly which line the error occurs in `create_tf_record.py`?

**Comment by steam0111** [comment]
> Hello. Can you tell exactly which line the error occurs in `create_tf_record.py`?
line 144, and I give you a few screens
![image](https://user-images.githubusercontent.com/15229812/52657025-bede6300-2f08-11e9-972d-182d82864f12.png)

![image](https://user-images.githubusercontent.com/15229812/52657200-2d232580-2f09-11e9-8d0d-ff115ddfa06d.png)

**Comment by thatbrguy** [comment]
I think the problem is with `img_path = os.path.join(img_subdirectory, data['filename']` in `line 60`. Try checking if both the arguments to functions are `str` and not a dictonary
